"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-21 11:25:49.183367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_users_email'), 'users', ['email'], unique=True, schema='cig')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['cig.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_audit_log_created_at'), 'audit_log', ['created_at'], unique=False, schema='cig')
    op.create_table('generations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('page_promoted', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('social_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('research_brief', sa.Text(), nullable=True),
    sa.Column('writer_system', sa.Text(), nullable=True),
    sa.Column('writer_human', sa.Text(), nullable=True),
    sa.Column('final_content', sa.Text(), nullable=True),
    sa.Column('output_storage_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['cig.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_generations_created_at'), 'generations', ['created_at'], unique=False, schema='cig')
    op.create_table('translation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('completed_jobs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['cig.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_translation_batches_created_at'), 'translation_batches', ['created_at'], unique=False, schema='cig')
    op.create_table('generated_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Text(), nullable=True),
    sa.Column('canvas_size', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('generation_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['cig.users.id'], ),
    sa.ForeignKeyConstraint(['generation_id'], ['cig.generations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_generated_posts_created_at'), 'generated_posts', ['created_at'], unique=False, schema='cig')
    op.create_index(op.f('ix_cig_generated_posts_generation_id'), 'generated_posts', ['generation_id'], unique=False, schema='cig')
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_generation_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['cig.users.id'], ),
    sa.ForeignKeyConstraint(['result_generation_id'], ['cig.generations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_generation_jobs_created_at'), 'generation_jobs', ['created_at'], unique=False, schema='cig')
    op.create_table('translation_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('source_image_storage_key', sa.Text(), nullable=True),
    sa.Column('target_language', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('canvas_size', sa.Text(), nullable=True),
    sa.Column('output_storage_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['cig.translation_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['cig.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cig'
    )
    op.create_index(op.f('ix_cig_translation_jobs_batch_id'), 'translation_jobs', ['batch_id'], unique=False, schema='cig')
    op.create_index(op.f('ix_cig_translation_jobs_created_at'), 'translation_jobs', ['created_at'], unique=False, schema='cig')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cig_translation_jobs_created_at'), table_name='translation_jobs', schema='cig')
    op.drop_index(op.f('ix_cig_translation_jobs_batch_id'), table_name='translation_jobs', schema='cig')
    op.drop_table('translation_jobs', schema='cig')
    op.drop_index(op.f('ix_cig_generation_jobs_created_at'), table_name='generation_jobs', schema='cig')
    op.drop_table('generation_jobs', schema='cig')
    op.drop_index(op.f('ix_cig_generated_posts_generation_id'), table_name='generated_posts', schema='cig')
    op.drop_index(op.f('ix_cig_generated_posts_created_at'), table_name='generated_posts', schema='cig')
    op.drop_table('generated_posts', schema='cig')
    op.drop_index(op.f('ix_cig_translation_batches_created_at'), table_name='translation_batches', schema='cig')
    op.drop_table('translation_batches', schema='cig')
    op.drop_index(op.f('ix_cig_generations_created_at'), table_name='generations', schema='cig')
    op.drop_table('generations', schema='cig')
    op.drop_index(op.f('ix_cig_audit_log_created_at'), table_name='audit_log', schema='cig')
    op.drop_table('audit_log', schema='cig')
    op.drop_index(op.f('ix_cig_users_email'), table_name='users', schema='cig')
    op.drop_table('users', schema='cig')
    # ### end Alembic commands ###
