SECTOR_WEBSITES = {
    "Al Nafi International College": "https://www.alnafi.com/",
    "Al Nafi Islamic College":       "https://islamic.alnafi.com/",
    "Al Nafi Academy":               "https://alnafi.academy/",
    "Alnafi Cloud":                  "https://alnafi.cloud/",
    "Annaafi PAY":                   "https://epay.com.pk/",
}

ALNAFI_SECTORS = {
    "Al Nafi International College": {
        "domain": "alnafi.com",
        "tagline": "Globally Recognized Pearson BTEC & EduQual Diplomas",
        "color_primary": "#2D6FBC",
        "color_secondary": "#1A4A8A",
        "color_accent": "#66BB6A",
        "description": "IT, Cloud, DevOps, AI, Cybersecurity Diplomas & Courses",
    },
    "Al Nafi Islamic College": {
        "domain": "islamic.alnafi.com",
        "tagline": "Next Generation Islamic Scholars",
        "color_primary": "#1B5E20",
        "color_secondary": "#2E7D32",
        "color_accent": "#66BB6A",
        "description": "Islamic Studies with Modern Tech Education",
    },
    "Al Nafi Academy": {
        "domain": "alnafi.academy",
        "tagline": "O-Levels & IGCSE Excellence",
        "color_primary": "#4A148C",
        "color_secondary": "#6A1B9A",
        "color_accent": "#66BB6A",
        "description": "Foundation, O-Levels, IGCSE Preparation",
    },
    "Alnafi Cloud": {
        "domain": "cloud.alnafi.com",
        "tagline": "Cloud for All",
        "color_primary": "#1976D2",
        "color_secondary": "#0D47A1",
        "color_accent": "#29B6F6",
        "description": "Cloud Computing & Infrastructure Solutions",
    },
    "Annaafi PAY": {
        "domain": "pay.alnafi.com",
        "tagline": "Smart & Secure Digital Payments",
        "color_primary": "#5C6BC0",
        "color_secondary": "#3949AB",
        "color_accent": "#7C4DFF",
        "description": "Digital Payment Platform by Al-Nafi Group",
    },
}

POST_TYPES = [
    "General Post",
    "Course Promotion",
    "Online Event Invitation",
    "Physical Event Invitation",
    "Online Webinar Invitation",
    "Physical Webinar Invitation",
    "Video Thumbnail",
    "Blog Thumbnail",
    "Announcement",
    "Testimonial / Success Story",
    "Admission Open",
    "Workshop Promotion",
    "Certificate Showcase",
]

SESSION_BADGES = [
    "None",
    "LIVE",
    "FREE",
    "RECORDED",
    "PREMIUM",
    "UPCOMING",
    "NEW",
    "LIMITED SEATS",
    "EARLY BIRD",
    "CERTIFIED",
    "HANDS-ON",
    "WORKSHOP",
    "MASTERCLASS",
    "BOOTCAMP",
    "OPEN HOUSE",
]

PLATFORM_TARGETS = [
    "Instagram",
    "Facebook",
    "Twitter / X",
    "WhatsApp",
    "LinkedIn",
    "YouTube",
]

CANVAS_PRESETS = {
    "Instagram / Facebook Square": "1080x1080",
    "Instagram Portrait": "1080x1350",
    "Stories (IG / FB / WA)": "1080x1920",
    "LinkedIn Post": "1200x627",
    "YouTube Thumbnail": "1280x720",
    "Twitter / X Post": "1200x675",
    "Facebook Post": "1200x630",
    "Event Banner / OG Image": "1200x630",
    "Custom": "custom",
}

OPENAI_SIZE_MAP = {
    "1080x1080": "1024x1024",
    "1080x1350": "1024x1536",
    "1080x1920": "1024x1536",
    "1200x627": "1536x1024",
    "1280x720": "1536x1024",
    "1200x675": "1536x1024",
    "1200x630": "1536x1024",
}

# Background presets: key = one-liner description (shown to user), used as prompt
BACKGROUND_PRESETS = {
    "Tech Visuals": [
        "Dark data center with rows of glowing blue server racks",
        "Abstract neon circuit board with flowing data streams",
        "Floating cloud computing icons over a gradient sky",
        "Neural network nodes and connections in deep blue tones",
        "Green digital shield with matrix-style falling code",
        "DevOps pipeline gears and container icons on dark canvas",
        "Minimalist desk setup with code glowing on a laptop screen",
        "Holographic binary digits swirling around a dark sphere",
        "Interconnected blockchain nodes with gold pulse lines",
        "Quantum particle trails on a deep violet background",
    ],
    "Educational Visuals": [
        "Warm-lit university hallway with arched ceilings",
        "Graduation cap on a stack of textbooks on a wooden desk",
        "Soft-focused library shelves stretching into the distance",
        "Clean whiteboard covered in knowledge diagrams and notes",
        "Confetti and caps in the air at a graduation ceremony",
        "Framed diploma beside a neat row of academic books",
        "Speaker at a polished podium addressing a seated audience",
        "Study desk with open notebook, laptop, and a cup of coffee",
        "Grand academic building exterior with columns and steps",
        "Globe wearing a graduation cap with light trails around it",
    ],
    "Blog Thumbnail -- Tech & Cloud": [
        "3D Microsoft Azure logo floating on a gradient blue background",
        "Glowing AWS cloud icon with rays on a dark navy background",
        "3D Google Cloud logo with colourful gradient on white",
        "3D Docker container stack with neon outlines on dark background",
        "Kubernetes wheel icon with glowing blue nodes on deep navy",
        "DevOps infinity loop with gears and code on dark canvas",
        "Python logo with floating code snippets on dark gradient",
        "Cybersecurity lock and shield glowing on deep blue circuit background",
        "Ethical hacking terminal screen with green text on black",
        "AI brain made of neural connections on purple-dark gradient",
        "Machine learning graph and data points floating in blue void",
        "Linux penguin mascot with terminal window on dark background",
        "JavaScript code glowing on a dark modern IDE screenshot",
        "React component tree with blue nodes on dark background",
        "Microservices architecture diagram with colour-coded blocks",
        "API gateway diagram with arrows and endpoints on dark blue",
        "Database server stack with glowing query lines on dark canvas",
        "Blockchain ledger blocks chained in 3D on dark gradient",
        "Cloud migration arrows lifting servers to the sky",
        "Laptop screen showing a live dashboard with charts",
        "Network topology map with blinking nodes on dark background",
        "Penetration testing toolkit on a dark hacker-style terminal",
        "Red and blue team cybersecurity shield clash on dark canvas",
        "Zero-trust architecture diagram on clean white background",
        "5G network tower with glowing signal waves at night",
    ],
    "Blog Thumbnail -- Business & Career": [
        "Professional shaking hands in a modern glass office",
        "Upward growth chart with arrow breaking through the top",
        "Roadmap of career milestones on a clean minimalist background",
        "LinkedIn profile on a laptop with a coffee cup beside it",
        "Resume document with a pen on a clean white desk",
        "Job interview scene in a bright modern office",
        "Salary negotiation concept with rising coins on a desk",
        "Remote work setup with laptop, headset, and home office",
        "Leadership silhouette standing on a podium with spotlight",
        "Team brainstorming around a whiteboard in a startup office",
        "Clock and calendar with productivity icons on white background",
        "Freelancer working at a coffee shop with laptop",
        "Entrepreneur writing a business plan in a modern workspace",
        "SWOT analysis chart on a clean presentation slide style",
        "People networking at a professional conference event",
    ],
    "Blog Thumbnail -- Education & Courses": [
        "Open textbook with glowing lightbulb above it on dark blue",
        "Student holding a diploma with bright sunlight behind",
        "Online course interface on a tablet with headphones beside",
        "Chalkboard with formulas and a graduation cap on corner",
        "Stack of colourful academic books with an apple on top",
        "E-learning concept with laptop and knowledge icons floating",
        "Study roadmap with numbered steps on a clean infographic background",
        "Certificate document with gold seal on a wooden desk",
        "Brain with gears and books around it on gradient background",
        "Classroom scene with interactive digital whiteboard",
        "Student coding on a laptop in a modern university library",
        "Scholarship coins and a graduation cap on blue background",
        "Teacher pointing at a large world map in a bright room",
        "Knowledge transfer concept with arrows between two heads",
        "Puzzle pieces forming a complete skill set on white background",
    ],
    "Regional / Audience Visuals": [
        "Diverse group of professionals in a modern office setting",
        "Toronto skyline glowing at golden hour",
        "World map with glowing connected nodes and light trails",
        "Dubai skyline silhouette with Burj Khalifa at sunset",
        "Attentive audience in a well-lit conference hall",
        "Confident speaker on stage with dramatic spotlight",
        "Proud graduate holding a diploma against a bright backdrop",
        "Graduate in cap and gown walking toward the horizon",
        "Focused student working on a laptop in a modern space",
        "Professor explaining concepts on a large digital display",
        "Row of colorful world flags representing global reach",
        "Professional climbing illuminated steps symbolizing growth",
        "Parent and child studying together at a home desk",
        "Teacher and students in an interactive classroom discussion",
        "Student standing confidently with a book in hand",
        "Sleek modern academy building exterior at dusk",
        "Welcoming open-house registration desk with a banner",
        "Career counsellor meeting with a student one-on-one",
        "Professional in a modern office typing on a laptop",
        "Graduate looking toward a bright, aspirational horizon",
        "Student in an online learning session on a glowing screen",
        "Diverse study group collaborating around a shared table",
    ],
}

FONT_OPTIONS = [
    "Montserrat (Modern, Clean)",
    "Poppins (Friendly, Rounded)",
    "Playfair Display (Elegant, Serif)",
    "Roboto (Neutral, Professional)",
    "Inter (Clean, Technical)",
    "Raleway (Thin, Sophisticated)",
    "Oswald (Bold, Condensed)",
    "Lato (Warm, Corporate)",
    "Nunito (Soft, Approachable)",
    "Cairo (Arabic-Latin Bilingual)",
]

PROVIDERS = {
    "gpt-image-2 (OpenAI) -- Default": "gpt-image-2",
    "gpt-image-1 (OpenAI)": "gpt-image-1",
    "Gemini Imagen 3 (Google)": "imagen-3",
    "Nano Banana": "nano-banana",
    "Prompt Only (JSON Output)": "prompt-only",
}

TRANSLATION_LANGUAGES = [
    # Most-used first
    "Urdu", "Arabic", "Hindi", "English", "French", "Spanish", "German",
    "Turkish", "Malay / Bahasa Malaysia", "Bengali", "Pashto", "Persian / Farsi",
    "Chinese (Simplified)", "Chinese (Traditional)", "Portuguese", "Indonesian",
    "Somali", "Swahili", "Russian", "Japanese", "Korean",
    # Full OpenAI-supported set (alphabetical after the above)
    "Afrikaans", "Albanian", "Amharic", "Armenian", "Azerbaijani",
    "Basque", "Belarusian", "Bosnian", "Bulgarian", "Catalan",
    "Cebuano", "Corsican", "Croatian", "Czech", "Danish", "Dutch",
    "Esperanto", "Estonian", "Filipino / Tagalog", "Finnish",
    "Frisian", "Galician", "Georgian", "Greek", "Gujarati",
    "Haitian Creole", "Hausa", "Hawaiian", "Hebrew", "Hmong",
    "Hungarian", "Icelandic", "Igbo", "Irish", "Italian",
    "Javanese", "Kannada", "Kazakh", "Khmer", "Kurdish (Kurmanji)",
    "Kyrgyz", "Lao", "Latin", "Latvian", "Lithuanian",
    "Luxembourgish", "Macedonian", "Malagasy", "Malayalam", "Maltese",
    "Maori", "Marathi", "Mongolian", "Myanmar (Burmese)", "Nepali",
    "Norwegian", "Nyanja (Chichewa)", "Odia (Oriya)", "Polish",
    "Punjabi", "Romanian", "Samoan", "Scottish Gaelic", "Serbian",
    "Sesotho", "Shona", "Sindhi", "Sinhala", "Slovak",
    "Slovenian", "Sundanese", "Swedish", "Tajik", "Tamil",
    "Tatar", "Telugu", "Thai", "Turkmen", "Ukrainian",
    "Uyghur", "Uzbek", "Vietnamese", "Welsh", "Xhosa",
    "Yiddish", "Yoruba", "Zulu",
]

SECTOR_ACCREDITATIONS = {
    "Al Nafi International College": ["EduQual UK", "ISACA", "EADL"],
    "Al Nafi Islamic College":       ["EduQual UK"],
    "Al Nafi Academy":               ["Pearson BTEC"],
    "Alnafi Cloud":                  [],
    "Annaafi PAY":                   [],
}
